<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWHfxjxs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWHfxjxs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWHfxjxs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWHfxjxs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWHfxjxs\App_KernelDevDebugContainer([
    'container.build_hash' => 'WHfxjxs',
    'container.build_id' => 'c22cee4b',
    'container.build_time' => 1596162452,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWHfxjxs');
