<?php

namespace ContainerWHfxjxs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9k6kfFZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9k6kfFZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9k6kfFZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ipaHelper' => ['privates', 'App\\Service\\FreeIPA\\FreeIPAHelper', 'getFreeIPAHelperService', true],
        ], [
            'ipaHelper' => 'App\\Service\\FreeIPA\\FreeIPAHelper',
        ]);
    }
}
