<?php

namespace ContainerWHfxjxs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccessRequestApproveFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\AccessRequestApproveFormType' shared autowired service.
     *
     * @return \App\Form\AccessRequestApproveFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/AccessRequestApproveFormType.php';

        return $container->privates['App\\Form\\AccessRequestApproveFormType'] = new \App\Form\AccessRequestApproveFormType();
    }
}
