<?php

namespace ContainerWHfxjxs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFreeIPAServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\FreeIPA\FreeIPAService' shared autowired service.
     *
     * @return \App\Service\FreeIPA\FreeIPAService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/FreeIPA/FreeIPAService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/ConfigHelper.php';

        return $container->privates['App\\Service\\FreeIPA\\FreeIPAService'] = new \App\Service\FreeIPA\FreeIPAService(\dirname(__DIR__, 4), ($container->privates['App\\Service\\ConfigHelper'] ?? ($container->privates['App\\Service\\ConfigHelper'] = new \App\Service\ConfigHelper(\dirname(__DIR__, 4)))));
    }
}
