<?php

namespace ContainerZvVAp7x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HOam7K2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HOam7K2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HOam7K2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'ipaService' => ['privates', 'App\\Service\\FreeIPA\\FreeIPAService', 'getFreeIPAServiceService', true],
            'mailHelper' => ['privates', 'App\\Service\\Mail\\MailHelper', 'getMailHelperService', true],
            'requestRepository' => ['privates', 'App\\Repository\\AccessRequestRepository', 'getAccessRequestRepositoryService', true],
        ], [
            'em' => '?',
            'ipaService' => 'App\\Service\\FreeIPA\\FreeIPAService',
            'mailHelper' => 'App\\Service\\Mail\\MailHelper',
            'requestRepository' => 'App\\Repository\\AccessRequestRepository',
        ]);
    }
}
