<?php

namespace ContainerZvVAp7x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccessRequestFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\AccessRequestFormType' shared autowired service.
     *
     * @return \App\Form\AccessRequestFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/AccessRequestFormType.php';

        return $container->privates['App\\Form\\AccessRequestFormType'] = new \App\Form\AccessRequestFormType();
    }
}
