<?php

namespace ContainerZvVAp7x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFreeIPAHelperService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\FreeIPA\FreeIPAHelper' shared autowired service.
     *
     * @return \App\Service\FreeIPA\FreeIPAHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/FreeIPA/FreeIPAHelper.php';

        return $container->privates['App\\Service\\FreeIPA\\FreeIPAHelper'] = new \App\Service\FreeIPA\FreeIPAHelper(($container->privates['App\\Service\\FreeIPA\\FreeIPAService'] ?? $container->load('getFreeIPAServiceService')));
    }
}
