<?php

namespace ContainerZvVAp7x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailHelperService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Mail\MailHelper' shared autowired service.
     *
     * @return \App\Service\Mail\MailHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Mail/MailHelper.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Mail/MailService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/ConfigHelper.php';

        $a = ($container->privates['App\\Service\\ConfigHelper'] ?? ($container->privates['App\\Service\\ConfigHelper'] = new \App\Service\ConfigHelper(\dirname(__DIR__, 4))));

        return $container->privates['App\\Service\\Mail\\MailHelper'] = new \App\Service\Mail\MailHelper(new \App\Service\Mail\MailService($a), $a, ($container->services['kernel'] ?? $container->get('kernel', 1)));
    }
}
